trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'eopires/projects:unyleya-project-$(Build.BuildId)'
  dockerRegistryServiceConnection: 'dockerconnection'

stages:
- stage: Build
  displayName: CI Docker
  jobs:  

  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1      
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'Build an image'
        dockerFile: './Dockerfile'
        imageName: '$(ImageName)'
        useDefaultContext: false
        buildContext: '.'
      displayName: 'Build the Docker image'

    - task: Docker@1      
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      displayName: 'Push the Docker image to Dockerhub'
